import {
    ShoppingCart,
    Package,
    PlusCircle,
    Star,
    CheckCircle2,
    Box,
} from "lucide-react";

export const ADMIN_PRODUCTS = [
    {
        id: "#PRD-001",
        name: "Delicate Rose Gold Bracelet",
        sku: "SKU: RGS-RGC-001",
        price: 89.99,
        stock: 45,
        category: "Jewelry",
        status: "Active",
        color: "bg-amber-300",
    },
    {
        id: "#PRD-002",
        name: "Classic Pearl Necklace Set",
        sku: "SKU: PRE-NCK-002",
        price: 129.99,
        stock: 8,
        category: "Jewelry",
        status: "Low Stock",
        color: "bg-gray-300",
    },
    {
        id: "#PRD-003",
        name: "Boho Beaded Bracelet Set",
        sku: "SKU: BHO-BRC-003",
        price: 44.99,
        stock: 0,
        category: "Jewelry",
        status: "Out of Stock",
        color: "bg-emerald-500",
    },
    {
        id: "#PRD-004",
        name: "Handmade Leather Tote Bag",
        sku: "SKU: LTH-BAG-004",
        price: 159.99,
        stock: 32,
        category: "Bags",
        status: "Active",
        color: "bg-pink-500",
    },
    {
        id: "#PRD-005",
        name: "Woven Crossbody Bag",
        sku: "SKU: WVN-BAG-005",
        price: 79.99,
        stock: 56,
        category: "Bags",
        status: "Active",
        color: "bg-amber-600",
    },
    {
        id: "#PRD-006",
        name: "Organic Cotton Throw Blanket",
        sku: "SKU: CTN-BLK-006",
        price: 64.99,
        stock: 28,
        category: "Textiles",
        status: "Active",
        color: "bg-yellow-200",
    },
    {
        id: "#PRD-008",
        name: "Sterling Silver Chain Necklace",
        sku: "SKU: SLV-PCK-008",
        price: 109.99,
        stock: 42,
        category: "Jewelry",
        status: "Active",
        color: "bg-gray-700",
    },
    {
        id: "#PRD-009",
        name: "Handwoven Macrame Wall Art",
        sku: "SKU: MCR-DCH-009",
        price: 74.99,
        stock: 18,
        category: "Home Decor",
        status: "Active",
        color: "bg-amber-700",
    },
    {
        id: "#PRD-007",
        name: "Gold Plated Earrings Set",
        sku: "SKU: GLD-EAR-007",
        price: 94.99,
        stock: 6,
        category: "Jewelry",
        status: "Low Stock",
        color: "bg-yellow-500",
    },
    {
        id: "#PRD-010",
        name: "Ceramic Vase Collection",
        sku: "SKU: CRM-VAS-010",
        price: 89.99,
        stock: 15,
        category: "Home Decor",
        status: "Active",
        color: "bg-gray-200",
    },
    {
        id: "#PRD-011",
        name: "Hand-dyed Silk Scarf",
        sku: "SKU: SLK-SCF-011",
        price: 54.99,
        stock: 33,
        category: "Textiles",
        status: "Active",
        color: "bg-purple-400",
    },
    {
        id: "#PRD-012",
        name: "Beaded Tassel Earrings",
        sku: "SKU: BDD-EAR-012",
        price: 34.99,
        stock: 71,
        category: "Jewelry",
        status: "Active",
        color: "bg-rose-400",
    },
    {
        id: "#PRD-013",
        name: "Knitted Coin Purse",
        sku: "SKU: KNT-PRS-013",
        price: 24.99,
        stock: 4,
        category: "Bags",
        status: "Low Stock",
        color: "bg-green-300",
    },
    {
        id: "#PRD-014",
        name: "Rattan Wall Mirror",
        sku: "SKU: RTN-MIR-014",
        price: 119.99,
        stock: 9,
        category: "Home Decor",
        status: "Low Stock",
        color: "bg-amber-200",
    },
    {
        id: "#PRD-015",
        name: "Crystal Quartz Pendant",
        sku: "SKU: CRY-PND-015",
        price: 49.99,
        stock: 0,
        category: "Jewelry",
        status: "Out of Stock",
        color: "bg-sky-300",
    },
];

export const RECENT_ORDERS = [
    {
        id: "#ORD-2024-001",
        customer: "Sarah Miller",
        product: "Rose Gold Bracelet",
        amount: "$89.99",
        status: "Completed",
        date: "Feb 6, 2026",
    },
    {
        id: "#ORD-2024-002",
        customer: "John Davis",
        product: "Pearl Necklace Set",
        amount: "$129.99",
        status: "Processing",
        date: "Feb 6, 2026",
    },
    {
        id: "#ORD-2024-003",
        customer: "Emily Brown",
        product: "Boho Beaded Set",
        amount: "$44.99",
        status: "Pending",
        date: "Feb 5, 2026",
    },
    {
        id: "#ORD-2024-004",
        customer: "Michael Wilson",
        product: "Crochet Pouch",
        amount: "$39.99",
        status: "Completed",
        date: "Feb 5, 2026",
    },
    {
        id: "#ORD-2024-005",
        customer: "Olivia Johnson",
        product: "Classic Earrings",
        amount: "$54.99",
        status: "Cancelled",
        date: "Feb 4, 2026",
    },
];

export const TOP_PRODUCTS = [
    {
        name: "Rose Gold Bracelet",
        category: "Jewelry",
        sales: 245,
        color: "bg-orange-200",
    },
    {
        name: "Pearl Necklace",
        category: "Jewelry",
        sales: 198,
        color: "bg-gray-200",
    },
    {
        name: "Boho Beaded Set",
        category: "Accessories",
        sales: 156,
        color: "bg-green-200",
    },
    {
        name: "Crochet Pouch",
        category: "Accessories",
        sales: 142,
        color: "bg-yellow-200",
    },
];

export const RECENT_ACTIVITY = [
    {
        text: "New order received",
        time: "2 minutes ago",
        icon: CheckCircle2,
        color: "text-green-500",
        bg: "bg-green-100",
    },
    {
        text: "Order #1234 shipped",
        time: "15 minutes ago",
        icon: Box,
        color: "text-blue-500",
        bg: "bg-blue-100",
    },
    {
        text: "New 5-star review",
        time: "1 hour ago",
        icon: Star,
        color: "text-yellow-500",
        bg: "bg-yellow-100",
    },
    {
        text: "New product added",
        time: "3 hours ago",
        icon: PlusCircle,
        color: "text-primary",
        bg: "bg-pink-100",
    },
];

export const CUSTOMERS_DATA = [
    {
        id: "CUST-001",
        name: "Sarah Miller",
        email: "sarah.m@example.com",
        orders: 12,
        spent: "$1,245.50",
        status: "Active",
        type: "VIP",
        since: "Jan 15, 2024",
        initials: "SM",
        bg: "bg-purple-500",
    },
    {
        id: "CUST-002",
        name: "John Davis",
        email: "john.davis@example.com",
        orders: 4,
        spent: "$345.00",
        status: "Active",
        type: "Regular",
        since: "Feb 02, 2024",
        initials: "JD",
        bg: "bg-blue-500",
    },
    {
        id: "CUST-003",
        name: "Emily Brown",
        email: "emily.b@example.com",
        orders: 28,
        spent: "$3,450.75",
        status: "Active",
        type: "VIP",
        since: "Nov 12, 2023",
        initials: "EB",
        bg: "bg-pink-500",
    },
    {
        id: "CUST-004",
        name: "Michael Wilson",
        email: "m.wilson@example.com",
        orders: 1,
        spent: "$89.99",
        status: "Inactive",
        type: "New",
        since: "Feb 05, 2024",
        initials: "MW",
        bg: "bg-orange-500",
    },
    {
        id: "CUST-005",
        name: "Olivia Johnson",
        email: "olivia.j@example.com",
        orders: 8,
        spent: "$856.20",
        status: "Active",
        type: "Regular",
        since: "Dec 05, 2023",
        initials: "OJ",
        bg: "bg-green-500",
    },
];
